export type LockerZoneId =
  | 'scout-report'
  | 'laptop'
  | 'jerseys'
  | 'straw-hat'
  | 'duffel-bag'
  | 'dad-jersey'
  | 'locker-placard-4'
  | 'locker-placard-2'
  | 'locker-placard-1'
  | 'locker-placard-3'
  | 'locker-placard-5'
  | 'question-jersey'
  | 'zoe'
  | 'higher-division-trophy'
  | 'basketball'
  | 'patent'
  | 'headphones'
  | 'melo-2'
  | 'way-of-wade-10'
  | 'harden-7'
  | 'ps5'
  | 'ps5-controller-1'
  | 'ps5-controller-2'
  | 'snap-values'
  | 'snap-jersey'
  | 'snap-shoes'
  | 'ghost-logo-jersey'

export type LockerContentKey = LockerZoneId | 'title' | 'back-to-court' | 'locker-info'
